services:
  - type: web
    name: docreq
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn documate.wsgi:application --bind 0.0.0.0:$PORT --timeout 120 --workers 4"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
      - key: ALLOW_ALL_HOSTS
        value: "False"
      - key: DJANGO_SUPERUSER_USERNAME
        sync: false
      - key: DJANGO_SUPERUSER_PASSWORD
        sync: false
      - key: DJANGO_SUPERUSER_EMAIL
        sync: false
      - key: EMAIL_HOST_USER
        sync: false
      - key: EMAIL_HOST_PASSWORD
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_PHONE_NUMBER
        sync: false
      - key: CSRF_TRUSTED_ORIGINS
        sync: false
