services:
  - type: web
    name: docreq
    runtime: python
    plan: free
    autoDeploy: true
    buildCommand: "./build.sh"
    startCommand: "gunicorn documate.wsgi:application --bind 0.0.0.0:$PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: WEB_CONCURRENCY
        value: "4"
