# Generated by Django 5.2.7 on 2025-10-30 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='date_updated',
        ),
    ]
