# Generated by Django 6.0.1 on 2026-02-03 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0002_remove_documentrequest_date_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='date_approved',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='date_rejected',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='date_released',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
