# Generated by Django 5.2.12 on 2026-03-09 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0004_documentrequest_face_verified_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='face_verified',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='gcash_reference',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='payment_status',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(choices=[('PNB', 'Philippine National Bank')], default='PNB', max_length=50),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
    ]
