# Generated by Django 5.2.12 on 2026-03-09 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0006_documentrequest_is_seen_documentrequest_last_updated_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='is_seen',
        ),
        migrations.RemoveField(
            model_name='documentrequest',
            name='last_updated',
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('FORM137', 'Form 137'), ('GOOD_MORAL', 'Certificate of Good Moral'), ('TRANSCRIPT', 'Transcript of Records'), ('OTHERS', 'Others')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(choices=[('PNB', 'Philippine National Bank')], default='PNB', max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_receipt',
            field=models.ImageField(blank=True, null=True, upload_to='payments/'),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='DocumentNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=100)),
                ('message', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
