# Generated by Django 5.2.12 on 2026-03-09 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0007_remove_documentrequest_is_seen_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
