# Generated by Django 5.2.12 on 2026-03-13 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0008_documentrequest_is_read'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('FORM137', 'Form 137'), ('GOOD_MORAL', 'Certificate of Good Moral'), ('TRANSCRIPT', 'Transcript of Records (TOR)'), ('CERTIFIED TRUE COPY', 'Certified True Copy'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE OF ENROLLMENT', 'Certificate of Enrollment'), ('CERTIFICATE WITH GRADES', 'Certificate with Grades'), ('MEDIUM OF INSTRUCTION', 'Medium of Instruction (MOT)'), ('CARD', 'Card')], max_length=50),
        ),
    ]
