# Generated by Django 5.2.12 on 2026-03-13 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0009_profile_email_verified_profile_phone_verified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='course',
            field=models.CharField(blank=True, choices=[('BSHM', 'BSHM'), ('BSIT', 'BSIT'), ('BEED', 'BEED'), ('BSED', 'BSED'), ('BSENTREP', 'BSENTREP')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='education_status',
            field=models.CharField(choices=[('UNDERGRAD', 'Undergraduate'), ('GRADUATED', 'Graduated'), ('POSTGRAD', 'Post Graduate')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='payment_option',
            field=models.CharField(choices=[('CASH', 'Pay as Cash'), ('BANK', 'Bank Payment')], default='CASH', max_length=10),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='tor_type',
            field=models.CharField(blank=True, choices=[('REGULAR', 'Regular'), ('IRREGULAR', 'Irregular')], max_length=20, null=True),
        ),
    ]
