# Generated by Django 5.2.12 on 2026-03-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0010_documentrequest_course_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='phone_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
