# Generated by Django 5.2.12 on 2026-03-13 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0011_profile_phone_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='document_type',
            field=models.CharField(choices=[('FORM137', 'Form 137'), ('TRANSCRIPT', 'Transcript of Records (TOR)'), ('CERTIFIED TRUE COPY', 'Certified True Copy'), ('DIPLOMA', 'Diploma'), ('CERTIFICATE OF ENROLLMENT', 'Certificate of Enrollment'), ('CERTIFICATE WITH GRADES', 'Certificate with Grades'), ('MEDIUM OF INSTRUCTION', 'Medium of Instruction (MOT)'), ('CARD', 'Card')], max_length=50),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_method',
            field=models.CharField(choices=[('CASH', 'Cash'), ('BANK', 'Bank Transfer'), ('ONLINE', 'Online Payment'), ('NONE', 'No Payment')], default='NONE', max_length=20),
        ),
    ]
