# Generated by Django 5.2.12 on 2026-03-15 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0012_documentrequest_payment_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documentrequest',
            name='education_status',
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('No Payment', 'No Payment')], default='Pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
    ]
