# Generated by Django 6.0.6 on 2026-07-03 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0013_remove_documentrequest_education_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('student', 'Current Student'), ('graduated', 'Graduated')], default='student', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
