# Generated by Django 6.0.6 on 2026-07-03 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0014_profile_student_status_alter_profile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequest',
            name='date_processing',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='documentrequest',
            name='date_ready',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released')], default='PENDING', max_length=20),
        ),
    ]
