# Generated by Django 6.0.7 on 2026-07-22 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0015_documentrequest_date_processing_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('READY', 'Ready'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released'), ('CANCEL', 'Cancel')], default='PENDING', max_length=20),
        ),
    ]
