# Generated by Django 6.0.7 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0016_alter_documentrequest_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures/'),
        ),
        migrations.AddField(
            model_name='profile',
            name='year',
            field=models.CharField(
                blank=True,
                choices=[
                    ('1st Year', '1st Year'),
                    ('2nd Year', '2nd Year'),
                    ('3rd Year', '3rd Year'),
                    ('4th Year', '4th Year'),
                    ('Graduated', 'Graduated'),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
