# Generated by Django 6.0.7 on 2026-07-23 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0017_profile_profile_picture_profile_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='middle_initial',
            field=models.CharField(
                blank=True,
                choices=[
                    ('N/A', 'N/A'),
                    ('A', 'A.'),
                    ('B', 'B.'),
                    ('C', 'C.'),
                    ('D', 'D.'),
                    ('E', 'E.'),
                    ('F', 'F.'),
                    ('G', 'G.'),
                    ('H', 'H.'),
                    ('I', 'I.'),
                    ('J', 'J.'),
                    ('K', 'K.'),
                    ('L', 'L.'),
                    ('M', 'M.'),
                    ('N', 'N.'),
                    ('O', 'O.'),
                    ('P', 'P.'),
                    ('Q', 'Q.'),
                    ('R', 'R.'),
                    ('S', 'S.'),
                    ('T', 'T.'),
                    ('U', 'U.'),
                    ('V', 'V.'),
                    ('W', 'W.'),
                    ('X', 'X.'),
                    ('Y', 'Y.'),
                    ('Z', 'Z.'),
                ],
                default='N/A',
                max_length=3,
                null=True,
            ),
        ),
    ]
