# Generated by Django 6.0.2 on 2026-07-29 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requestsystem', '0019_alter_profile_student_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('PROCESSING', 'Processing'), ('READY', 'Ready for Pickup'), ('REJECTED', 'Rejected'), ('RELEASED', 'Released'), ('CANCEL', 'Cancel')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='profile',
            name='student_status',
            field=models.CharField(choices=[('student', 'Current Student'), ('irregular', 'Irregular Student'), ('graduated', 'Graduated')], default='student', max_length=20),
        ),
    ]
