"""
Django settings for documate project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load environment variables from .env file
load_dotenv(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-#7hjfi#as8m1sgdp2l=l*1v%^x*0^imb10#kh&4sjf1z-g#dl_')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = [
    '127.0.0.1',
    'localhost',
    '.vercel.app',
    '192.168.50.46',
    '192.168.50.132',
    '192.168.50.54',
]
RENDER_EXTERNAL_HOSTNAME = os.getenv('RENDER_EXTERNAL_HOSTNAME')
if RENDER_EXTERNAL_HOSTNAME:
    ALLOWED_HOSTS.append(RENDER_EXTERNAL_HOSTNAME)
    ALLOWED_HOSTS.append(f'*.{RENDER_EXTERNAL_HOSTNAME}')

VERCEL_URL = os.getenv('VERCEL_URL') or os.getenv('VERCEL_BRANCH_URL') or os.getenv('VERCEL_PROJECT_PRODUCTION_URL')
if VERCEL_URL:
    VERCEL_URL = VERCEL_URL.replace('https://', '').replace('http://', '').rstrip('/')
    ALLOWED_HOSTS.append(VERCEL_URL)
    ALLOWED_HOSTS.append(f'*.{VERCEL_URL}')

if os.getenv('ALLOW_ALL_HOSTS', 'False') == 'True' or os.getenv('VERCEL') == '1':
    ALLOWED_HOSTS.append('*')

CSRF_TRUSTED_ORIGINS = [
    'https://*.vercel.app',
    'http://*.vercel.app',
]
if RENDER_EXTERNAL_HOSTNAME:
    CSRF_TRUSTED_ORIGINS.append(f'https://{RENDER_EXTERNAL_HOSTNAME}')
    CSRF_TRUSTED_ORIGINS.append(f'http://{RENDER_EXTERNAL_HOSTNAME}')

if VERCEL_URL:
    CSRF_TRUSTED_ORIGINS.append(f'https://{VERCEL_URL}')
    CSRF_TRUSTED_ORIGINS.append(f'http://{VERCEL_URL}')

EXTRA_CSRF_ORIGINS = os.getenv('CSRF_TRUSTED_ORIGINS', '')
if EXTRA_CSRF_ORIGINS:
    for origin in EXTRA_CSRF_ORIGINS.split(','):
        origin = origin.strip()
        if origin:
            CSRF_TRUSTED_ORIGINS.append(origin)

if os.getenv('ALLOW_ALL_HOSTS', 'False') == 'True':
    CSRF_TRUSTED_ORIGINS += [
        'http://192.168.0.0/16',
        'http://10.0.0.0/8',
        'http://172.16.0.0/12',
    ]

SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
RUNNING_ON_VERCEL = (
    os.getenv('RUNNING_ON_VERCEL', 'False') == 'True'
    or os.getenv('VERCEL') == '1'
    or bool(os.getenv('VERCEL_URL'))
)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'requestsystem',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'documate.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / "templates"],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'requestsystem.context_processors.daily_request_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'documate.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

DATABASE_URL = os.getenv('DATABASE_URL') or os.getenv('POSTGRES_URL')
if DATABASE_URL:
    import dj_database_url
    DATABASES['default'] = dj_database_url.config(
        default=DATABASE_URL,
        conn_max_age=600,
        conn_health_checks=True,
    )
elif RUNNING_ON_VERCEL:
    import shutil
    tmp_db = Path('/tmp/db.sqlite3')
    bundled_db = BASE_DIR / 'db.sqlite3'
    if not tmp_db.exists() and bundled_db.exists():
        try:
            shutil.copy2(bundled_db, tmp_db)
        except Exception:
            pass
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': tmp_db,
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Manila'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

STATICFILES_STORAGE = 'whitenoise.storage.CompressedStaticFilesStorage'

MEDIA_URL = '/media/'
if RUNNING_ON_VERCEL:
    MEDIA_ROOT = Path('/tmp/media')
    if not MEDIA_ROOT.exists():
        import shutil
        bundled_media = BASE_DIR / 'media'
        if bundled_media.exists():
            try:
                shutil.copytree(bundled_media, MEDIA_ROOT, dirs_exist_ok=True)
            except Exception:
                pass
        MEDIA_ROOT.mkdir(parents=True, exist_ok=True)
else:
    MEDIA_ROOT = BASE_DIR / 'media'

_EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
_EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')

if _EMAIL_HOST_PASSWORD:
    _EMAIL_HOST_PASSWORD = _EMAIL_HOST_PASSWORD.replace(' ', '').strip()

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = _EMAIL_HOST_USER
EMAIL_HOST_PASSWORD = _EMAIL_HOST_PASSWORD
DEFAULT_FROM_EMAIL = _EMAIL_HOST_USER

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


AUTHENTICATION_BACKENDS = [
    'requestsystem.backends.AllowInactiveAuthBackend',
]
